# Generated by Django 5.0.1 on 2025-02-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorder', '0002_alter_cheese_id_alter_order_id_alter_pizzasauce_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
