# Generated by Django 5.0.1 on 2025-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaorder', '0003_alter_pizzasize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='crust_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pizzasauce',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
